services:
  todoapp:
    image: todoapp
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on: 
      database:
        condition: service_started

  database:
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=todoapp_database
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      
